name: "Deploy to Vercel"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
jobs:
  build_and_deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Build the app"
        run: "yarn build"

      - name: "Deploy to Vercel"
        uses: "amondnet/vercel-action@v20"
        with:
          github-comment: false
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          scope: "${{ secrets.VERCEL_ORG_ID }}"
          vercel-token: "${{ secrets.VERCEL_TOKEN }}"
          vercel-args: "--confirm --prod"
          vercel-org-id: "${{ secrets.VERCEL_ORG_ID }}"
          vercel-project-id: "${{ secrets.VERCEL_PROJECT_ID }}"
          working-directory: "."
